# Generated by Django 4.2.11 on 2024-03-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='work',
        ),
        migrations.AddField(
            model_name='rating',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_ratings', to='blog.work'),
        ),
    ]
