# Generated by Django 4.2.11 on 2024-03-14 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_rating_work_rating_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='work_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
